name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Code Check
        uses: actions/checkout@v5

      - name: Build image and start the container
        run: docker compose up -d --build

      - name: Clean up images
        run: docker image prune -f
